In [1]:
import numpy as np

In [3]:
st = [1,2,3,4]
print(st)

[1, 2, 3, 4]


In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1,2,3,4],[2,3,5,7]])
b

array([[1, 2, 3, 4],
       [2, 3, 5, 7]])

In [12]:
c = np.array([[[1,2,3,4,5],[4,5,6,2,6],[3,5,6,9,0]]])
c

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 2, 6],
        [3, 5, 6, 9, 0]]])

In [13]:
print(c.size)

15


In [14]:
print(c.shape)

(1, 3, 5)


In [16]:
c.transpose()

array([[[1],
        [4],
        [3]],

       [[2],
        [5],
        [5]],

       [[3],
        [6],
        [6]],

       [[4],
        [2],
        [9]],

       [[5],
        [6],
        [0]]])

In [23]:
np.empty((4,4), dtype = int)

array([[3801155, 5570652, 6619251, 7536754],
       [5570652, 4522067, 6029394, 7340097],
       [4456560, 7602273, 6029409, 7274572],
       [6357091, 6029420, 6619220, 7340141]])

In [28]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((5,6), dtype = str)

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [55]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [57]:
x.reshape((20))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [63]:
a[0]

array([1, 2, 3, 4, 5])

In [64]:
a[0,0]

1

In [65]:
a[4,2]

23

In [69]:
a[1:2]

array([[ 6,  7,  8,  9, 10]])

In [70]:
a[2:5,4]

array([15, 20, 25])

In [71]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [75]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [76]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [77]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])